org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.ndkVersion=29.0.13174953 // 16 kb page size requirement changes - updated NDK to 29.0.13
android.cmakeVersion=3.31.1 // 16 kb page size requirement changes - updated CMake to 3.31.1
