on:
    pull_request:
      branches:
        - main
        - master
    push:
      branches:
        - main
        - master
        - develop
name: "Build APK & AAB Release"
jobs:
    build:
      name: Build APK & AAB Release
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            architecture: x64
        - name: Decode Keystore
          run: |
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
        - name: Set Environment Variables
          run: |
            echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV
            echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
            echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        - name: Build APK
          run: flutter build apk --release --split-per-abi
        - name: Build AAB
          run: flutter build appbundle --release
        - name: Push APK & AAB to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/release/*,build/app/outputs/bundle/release/*"
            tag: v1.0.${{ github.run_number }}
            token: ${{ secrets.TOKEN }}
  
  
  
  
  
  
  # push to master, main, develop
  # pull request on main master