name: "Build APK & AAB Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build APK & AAB Release
    runs-on: ubuntu-latest
    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          architecture: x64

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
        shell: pwsh

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: | 
            ${{ runner.os }}-flutter-

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi || exit 1

      - name: Build AAB
        run: flutter build appbundle --release || exit 1

      - name: Push APK & AAB to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk, build/app/outputs/bundle/release/*.aab"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


# push to master, main, develop
# pull request on main master